### PR TITLE
Change the binary and multistate numeric "value" to float type

### PR DESCRIPTION
**Pull request by kushan-26**
The initial numeric value was sent as a string. Change it to a floating number

### CODE REVIEW

**Review by ChristianTremblay — COMMENTED** [review]
Not sure it will solve the root cause of the issue you saw. At first, why does `val.split(':')[0]` returns 'active' ? for a binary... the format I want is `0:"inactive"` and `1:"active"`

Also, the number should be integer... not float.

**Review by ChristianTremblay — CHANGES_REQUESTED** [review]
Change for `int` instead of float please and I will merge. It's better anyway, even if everything is not solved. 

Thanks @kushan-26

**Comment by kushan-26** [comment]
It did fix the root cause of the issue I had. Anything received within double quotes is considered as a string in influxdb.  The following statement sends the numeric value as a string. 
```_value = "{}".format(val.split(":")[0])```

string value
binary_strg

numeric value (if you check a binary point for one of your devices, it should say string for numeric as well)
binary_Int

And I thought your intention is to split the ```0:"inactive"``` and ```1:"active"``` using ```val.split(":")[x]``` to have the string_value and numeric value separately?

I will change the ```float``` to ```int```. Nonetheless, it doesn't really matter in influxdb because all numerics are considered as float type unless specifically defined as ```int``` using letter ```i``` at the end. 
https://docs.influxdata.com/influxdb/cloud/reference/syntax/line-protocol/#float

**Comment by ChristianTremblay** [comment]
I should have been more explicit. You are right about influx but I remember a bug in BAC0 that I thought was fixed that created a bunch of history value with (for example) only "active" instead of "(1,"active")" ... I thought I saw that on your first pictures. 

If you already have a bunch of data in influx with string type, look at my comment on the issue. You can convert the type in the request. Pretty cool. 

Thanks for your help on that bug.

**Comment by kushan-26** [comment]
You're welcome and appreciate your time spent looking into this.

**Pull request merged**
