### PR TITLE
Update sql.py

### PR DESCRIPTION
**Pull request by kushan-26**
Update the script to accommodate binary values that read "0: inactive", "1: active" to "[0, 1]".

### CODE REVIEW

**Comment by ChristianTremblay** [comment]
This was done so the web interface was able to get some kind of "string" value if I remember correctly. If we change that, we will need to take care of the moment the device is reconnected from the DB to the BACnet network.

This was also a way to be closed to the "enum" side of thing where I was able to have the string equivalent of the value in the DB. It is not always easy to guess the state based on the value (was 0 occupied or 1 ?)

**Comment by kushan-26** [comment]
I thought this only relates when it comes to saving to a sql database. Because "Inactive, Active" values will convert to [0, 1] right now. As I remember, initially this was done to take the mean value for resampling. However, now binary values are taking the last value for resampling. Even back then the values were not translated to original state upon reconnecting from database. This is my understanding. Have I misunderstood the process?

Also, Isn't the web interface use the internal history which has the string values?

**Comment by ChristianTremblay** [comment]
[cricket sound]

I think you are right.

**Comment by ChristianTremblay** [comment]
I really need more time per day....

**Comment by ChristianTremblay** [comment]
@kushan-26  Please have a look to issue #291 as I need your input on what I came out to do.
Thanks

**Pull request merged**
