### PR TITLE
Update README.rst

### PR DESCRIPTION
**Pull request by sgpinkus**
Minor. Touch up grammar upon reading.

### CODE REVIEW

**Comment by ChristianTremblay** [comment]
Hacktoberfest.....

**Comment by sgpinkus** [comment]
It's December?

**Comment by ChristianTremblay** [comment]
> It's December?

You got me there :-)

**Comment by ChristianTremblay** [comment]
> Hacktoberfest.....

Apologize @sgpinkus 
Did not want to be rude.

**Comment by sgpinkus** [comment]
np

**Pull request closed without merging**
