### PR TITLE
Fixes #130 by assigning deafult value of 0 to response if presentValu…

### LINKED ISSUE #130: read mixin can check validity before assignment
First of all thank you for this nice work. It really makes life easier. I have an issue regarding the read_single behavior during controller initialization. Consider the following

```python
bacnet = BAC0.connect()
controller = BAC0.device(address='10.xx.xx.xx',
                          device_id=900,
                          network=bacnet)
```

This leads to the following stack

```bash
2019-03-04 14:19:15,314 - INFO    | Changing device state to DeviceDisconnected'>
2019-03-04 14:19:16,280 - INFO    | Changing device state to RPDeviceConnected'>
2019-03-04 14:19:17,300 - INFO    | Device 900:[GW_room] found... building points list
Traceback (most recent call last):

  File "<ipython-input-7-1f3fedd559ac>", line 7, in <module>
    ('analogValue', 4)],

  File "c:\users\evalan\appdata\local\programs\python\python37\lib\site-packages\BAC0\core\devices\Device.py", line 165, in __init__
    self.new_state(DeviceDisconnected)

  File "c:\users\evalan\appdata\local\programs\python\python37\lib\site-packages\BAC0\core\devices\Device.py", line 177, in new_state
    self._init_state()

  File "c:\users\evalan\appdata\local\programs\python\python37\lib\site-packages\BAC0\core\devices\Device.py", line 623, in _init_state
    self.connect()

  File "c:\users\evalan\appdata\local\programs\python\python37\lib\site-packages\BAC0\core\devices\Device.py", line 651, in connect
    self.new_state(RPDeviceConnected)

  File "c:\users\evalan\appdata\local\programs\python\python37\lib\site-packages\BAC0\core\devices\Device.py", line 177, in new_state
    self._init_state()

  File "c:\users\evalan\appdata\local\programs\python\python37\lib\site-packages\BAC0\core\devices\Device.py", line 402, in _init_state
    self._buildPointList()

  File "c:\users\evalan\appdata\local\programs\python\python37\lib\site-packages\BAC0\core\devices\Device.py", line 467, in _buildPointList
    self.custom_object_list)

  File "c:\users\evalan\appdata\local\programs\python\python37\lib\site-packages\BAC0\core\devices\mixins\read_mixin.py", line 500, in _discoverPoints
    self.read_single('{} {} presentValue '.format(point_type, point_address))),

ValueError: could not convert string to float: 
```

Then when I modified the `_discoverPoints` it turns out that the return value of `self.read_single('{} {} presentValue '.format(point_type, point_address))),` is an empty string hence `float('')`.

Is there a given default value that you can write in instead of forcing the float value? I can send a PR if you have a default value in mind. 

(version info bacpypes 0.17.5, BAC0 0.99.944)

### PR DESCRIPTION
**Pull request by Romeren**
So changed read_mixin.py line 317 and 319.
Where i added default value of 0 if presentValue evaluates to False

presentValue = float(presentValue or 0)
presentValue = int(presentValue or 0)

This closes issue #130

### CODE REVIEW

**Comment by ChristianTremblay** [comment]
This is weird. Do you have some wireshard trace showing the response from the bad devices (I’m curious)

If not, anyway, I like the idea. But I would prefer something like ‘nan’ instead of 0... because then it would be possible to “know” that there is something wrong... that is not a real 0. 

What do you think ?

**Comment by ChristianTremblay** [comment]
For int we could maybe choose something extreme as nan won’t work...

**Comment by Romeren** [comment]
Just a follow-up....
its not because of lost packages or malformed packages.... and its the same registers every time. but since im simply interfacing with an existing system, i cannot tell you much about what goes on there... -only that it is a bms priva blue installed by a certified installer (but i guess everyone can make mistakes)

regarding the changes, i agree that simply putting in a zero is a bad idea.
I suggest putting in a warning in the log and substituting with nan where possible and min integer where it isn't.... another solution would be to log it and completly skip the property.
so which ever you prefer.

**Comment by ChristianTremblay** [comment]
@Romeren 
Thanks for your patience... slowed down as my PC died.
Please remove infos.py from the PR

and change
```
presentValue = float(presentValue or 0)
presentValue = int(presentValue or 0)
```
for 
```
presentValue = float(presentValue or 'nan)
presentValue = int(presentValue or 255)
```
and I will merge

**Pull request closed without merging**
